# change all /var/www/inclare on your project folder

proxy_cache_path /var/www/inclare/apps/backend/uploads/cache levels=1:2 keys_zone=IMAGE_CACHE:20m inactive=2d max_size=3g;

server {
  listen 80;
  listen [::]:80;
  # change this domain to yours
  server_name domain.ru;

  access_log off;
  error_log /var/log/nginx/error.log warn;

  return 301 https://domain.ru$request_uri;
}

server {
  listen 443;
  listen [::]:443;
  # change this domain to yours
  server_name domain.ru;

  # change this to your certificates
  ssl_certificate /etc/letsencrypt/live/domain.ru/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/domain.ru/privkey.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;

  access_log off;
  error_log /var/log/nginx/error.log warn;

  server_tokens off;
  client_max_body_size 50m;

  gzip on;
  gzip_min_length 1024;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_types
  text/plain
  text/css
  text/xml
  application/json
  application/javascript
  application/xml
  application/xml+rss
  image/svg+xml;

  location / {
    # change this port to CLIENT_PUBLIC_PORT from .env
    proxy_pass http://127.0.0.1:3005;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location /trpc/ {
    limit_req zone=api burst=20 nodelay;

    # change this port to API_PUBLIC_PORT from .env
    proxy_pass http://127.0.0.1:5005/trpc/;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /uploads/ {
    # change this port to API_PUBLIC_PORT from .env
    proxy_pass http://127.0.0.1:5005/uploads/;

    proxy_buffering off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location /internal_uploads/ {
    internal;
    alias /var/www/inclare/apps/backend/uploads/;
  }

  location /internal_uploads/cache/ {
    internal;

    proxy_cache IMAGE_CACHE;
    proxy_cache_valid 200 2d;
    proxy_cache_key $request_uri;

    add_header X-Cache-Status $upstream_cache_status;

    # change this port to API_PUBLIC_PORT from .env
    proxy_pass http://127.0.0.1:5005/trpc/generate-cache$request_uri;
  }
}
